"""add missing tables

Revision ID: 0cf57b26206b
Revises: 014
Create Date: 2026-10-01 23:10:11.269056

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf57b26206b'
down_revision: Union[str, None] = '014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('site_name', sa.String(length=255), nullable=False),
    sa.Column('address_line_1', sa.String(length=255), nullable=False),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=20), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_sites_client_id'), 'client_sites', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_sites_company_id'), 'client_sites', ['company_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending', 'partial', 'paid', 'cancelled', name='invoice_status_enum'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tds_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('pdf_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_client_id'), 'invoices', ['client_id'], unique=False)
    op.create_index(op.f('ix_invoices_company_id'), 'invoices', ['company_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_table('tds_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('financial_year', sa.String(length=9), nullable=False),
    sa.Column('tds_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('deducted_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('certificate_number', sa.String(length=100), nullable=True),
    sa.Column('certificate_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tds_records_client_id'), 'tds_records', ['client_id'], unique=False)
    op.create_index(op.f('ix_tds_records_company_id'), 'tds_records', ['company_id'], unique=False)
    op.create_index(op.f('ix_tds_records_invoice_id'), 'tds_records', ['invoice_id'], unique=False)
    op.create_table('physical_challans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('challan_number', sa.String(length=50), nullable=False),
    sa.Column('challan_date', sa.Date(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending_verification', 'verified', 'rejected', name='physical_challan_status_enum'), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_physical_challans_challan_number'), 'physical_challans', ['challan_number'], unique=False)
    op.create_index(op.f('ix_physical_challans_company_id'), 'physical_challans', ['company_id'], unique=False)
    op.create_table('driver_collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('collection_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_mode', sa.String(length=50), nullable=False),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_collections_company_id'), 'driver_collections', ['company_id'], unique=False)
    op.create_index(op.f('ix_driver_collections_driver_id'), 'driver_collections', ['driver_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('challan_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['challan_id'], ['challans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_challans_client_id'), 'challans', ['client_id'], unique=False)
    op.drop_constraint(op.f('clients_company_id_fkey'), 'clients', type_='foreignkey')
    op.drop_constraint(op.f('companies_name_key'), 'companies', type_='unique')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.add_column('drivers', sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'inactive', name='driver_status_enum'), server_default='pending', nullable=False))
    op.drop_constraint(op.f('drivers_license_number_key'), 'drivers', type_='unique')
    op.drop_index(op.f('ix_drivers_license_number'), table_name='drivers')
    op.create_index(op.f('ix_drivers_license_number'), 'drivers', ['license_number'], unique=True)
    op.create_index(op.f('ix_drivers_assigned_vehicle_id'), 'drivers', ['assigned_vehicle_id'], unique=False)
    op.create_index(op.f('ix_drivers_user_id'), 'drivers', ['user_id'], unique=False)
    op.drop_constraint(op.f('quotations_quotation_number_key'), 'quotations', type_='unique')
    op.drop_index(op.f('ix_quotations_quotation_number'), table_name='quotations')
    op.create_index(op.f('ix_quotations_quotation_number'), 'quotations', ['quotation_number'], unique=True)
    op.create_index(op.f('ix_quotations_client_id'), 'quotations', ['client_id'], unique=False)
    op.drop_constraint(op.f('trip_receipts_trip_id_key'), 'trip_receipts', type_='unique')
    op.drop_index(op.f('ix_trip_receipts_trip_id'), table_name='trip_receipts')
    op.create_index(op.f('ix_trip_receipts_trip_id'), 'trip_receipts', ['trip_id'], unique=True)
    op.add_column('trips', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_trips_client_id'), 'trips', ['client_id'], unique=False)
    op.drop_constraint(op.f('users_mobile_number_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_mobile_number'), table_name='users')
    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=True)
    op.drop_constraint(op.f('vehicles_registration_no_key'), 'vehicles', type_='unique')
    op.drop_index(op.f('ix_vehicles_registration_no'), table_name='vehicles')
    op.create_index(op.f('ix_vehicles_registration_no'), 'vehicles', ['registration_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_registration_no'), table_name='vehicles')
    op.create_index(op.f('ix_vehicles_registration_no'), 'vehicles', ['registration_no'], unique=False)
    op.create_unique_constraint(op.f('vehicles_registration_no_key'), 'vehicles', ['registration_no'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_users_mobile_number'), table_name='users')
    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=False)
    op.create_unique_constraint(op.f('users_mobile_number_key'), 'users', ['mobile_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_trips_client_id'), table_name='trips')
    op.drop_column('trips', 'scheduled_at')
    op.drop_index(op.f('ix_trip_receipts_trip_id'), table_name='trip_receipts')
    op.create_index(op.f('ix_trip_receipts_trip_id'), 'trip_receipts', ['trip_id'], unique=False)
    op.create_unique_constraint(op.f('trip_receipts_trip_id_key'), 'trip_receipts', ['trip_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_quotations_client_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_quotation_number'), table_name='quotations')
    op.create_index(op.f('ix_quotations_quotation_number'), 'quotations', ['quotation_number'], unique=False)
    op.create_unique_constraint(op.f('quotations_quotation_number_key'), 'quotations', ['quotation_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_drivers_user_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_assigned_vehicle_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_license_number'), table_name='drivers')
    op.create_index(op.f('ix_drivers_license_number'), 'drivers', ['license_number'], unique=False)
    op.create_unique_constraint(op.f('drivers_license_number_key'), 'drivers', ['license_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('drivers', 'status')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_unique_constraint(op.f('companies_name_key'), 'companies', ['name'], postgresql_nulls_not_distinct=False)
    op.create_foreign_key(op.f('clients_company_id_fkey'), 'clients', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_challans_client_id'), table_name='challans')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_driver_collections_driver_id'), table_name='driver_collections')
    op.drop_index(op.f('ix_driver_collections_company_id'), table_name='driver_collections')
    op.drop_table('driver_collections')
    op.drop_index(op.f('ix_physical_challans_company_id'), table_name='physical_challans')
    op.drop_index(op.f('ix_physical_challans_challan_number'), table_name='physical_challans')
    op.drop_table('physical_challans')
    op.drop_index(op.f('ix_tds_records_invoice_id'), table_name='tds_records')
    op.drop_index(op.f('ix_tds_records_company_id'), table_name='tds_records')
    op.drop_index(op.f('ix_tds_records_client_id'), table_name='tds_records')
    op.drop_table('tds_records')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_company_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_client_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_client_sites_company_id'), table_name='client_sites')
    op.drop_index(op.f('ix_client_sites_client_id'), table_name='client_sites')
    op.drop_table('client_sites')
    # ### end Alembic commands ###
